/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Laptop.gltf --transform 
Files: Laptop.gltf [1.65MB] > D:\btt\Frontend\React 3D Portfolio_Tingting_Bi\laptop\Laptop-transformed.glb [86.78KB] (95%)
Author: lazercar (https://sketchfab.com/lazercar)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/laptop-c144fe98db1a4c0a8e5759772dd37cbc
Title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_0.geometry} material={materials.Material} position={[0, 0.153, 0.41]} rotation={[1.565, 0, Math.PI]} scale={[-1.955, 1.392, 0.034]} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.002']} position={[0, 0.153, 0.41]} rotation={[1.565, 0, Math.PI]} scale={[-1.955, 1.392, 0.034]} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.004']} position={[0, 0.153, 0.41]} rotation={[1.565, 0, Math.PI]} scale={[-1.955, 1.392, 0.034]} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.005']} position={[0, 0.153, 0.41]} rotation={[1.565, 0, Math.PI]} scale={[-1.955, 1.392, 0.034]} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials['Material.008']} position={[0, 0.153, 0.41]} rotation={[1.565, 0, Math.PI]} scale={[-1.955, 1.392, 0.034]} />
      <mesh geometry={nodes.Cube002_2.geometry} material={materials.material} position={[0, 0.153, 0.41]} rotation={[1.565, 0, Math.PI]} scale={[-1.955, 1.392, 0.034]} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} position={[-0.001, 0.186, -0.982]} rotation={[-2.476, 0, -Math.PI]} scale={[1.306, 0.094, 17.678]} />
    </group>
  )
}

useGLTF.preload('/Laptop-transformed.glb')
